version: '3.5'
volumes:
  data:
services:
  db:
    image: mysql:5.6
    ports:
      - "3308:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yeshua18
      - MYSQL_DATABASE=fornecedor
