server:
  port: 8888

spring:
  profiles:
   active: default
  cloud:
    config:
      server:
          git: 
            uri: https://github.com/BrunoCarvalho18/microservices-treinamento-repo
            search-paths: fornecedor

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
    service-url:
      defaultZone: http://localhost:8761/eureka     

                          
           